name: Run Tests # name of this GitHub Actions workflow

on: # defines when this workflow should run 
  pull_request: # when a pull request is opened or updated against the main branch
    branches:
      - main
  push: # when code is pushed directly to the main branch.
    branches:
      - main

jobs: # workflows are divided into jobs. This workflow has 1 job called test
  test:
    runs-on: ubuntu-latest # this workflow runs on the latest Ubuntu virtual machine

    steps:
      - name: Checkout repository # Pulls down your repositoryâ€™s code so the workflow has access to it.
        uses: actions/checkout@v5

      - name: Set up Node.js # Installs Node.js version 24 on the runner machine.
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies # install dependencies
        run: npm install

      - name: Install client dependencies # install dependencies
        run: |
          cd client
          npm install

      - name: Run Jest tests # run your test suite using Jest
        run: npm run test
